services:
  postgres:
    container_name: postgresdb
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=manganmasbro
    ports:
      - 5432:5432
