export const ingredients = [
  {
    id: 1,
    ingredient_1: "Gesang Gey",
    ingredient_2: "Gesang Gey",
    ingredient_3: "Gesang Gey",
    ingredient_4: "Gesang Gey",
    ingredient_5: "Gesang Gey",
    ingredient_6: "Gesang Gey",
    ingredient_7: "Gesang Gey",
    ingredient_8: "Gesang Gey",
    ingredient_9: "Gesang Gey",
    ingredient_10: "Gesang Gey",
    ingredient_11: "Gesang Gey",
    ingredient_12: "Gesang Gey",
    ingredient_13: "Gesang Gey",
    ingredient_14: "Gesang Gey",
    ingredient_15: "Gesang Gey",
    ingredient_16: "Gesang Gey",
    ingredient_17: "Gesang Gey",
    ingredient_18: "Gesang Gey",
    ingredient_19: "Gesang Gey",
    ingredient_20: "Gesang Gey",
  },
  {
    id: 2,
    ingredient_1: "Gesang Gey",
    ingredient_2: "Gesang Gey",
    ingredient_3: "Gesang Gey",
    ingredient_4: "Gesang Gey",
    ingredient_5: "Gesang Gey",
    ingredient_6: "Gesang Gey",
    ingredient_7: "Gesang Gey",
    ingredient_8: "Gesang Gey",
    ingredient_9: "Gesang Gey",
    ingredient_10: "Gesang Gey",
    ingredient_11: "Gesang Gey",
    ingredient_12: "Gesang Gey",
    ingredient_13: "Gesang Gey",
    ingredient_14: "Gesang Gey",
    ingredient_15: "Gesang Gey",
    ingredient_16: "Gesang Gey",
    ingredient_17: "Gesang Gey",
    ingredient_18: "Gesang Gey",
    ingredient_19: "Gesang Gey",
    ingredient_20: "Gesang Gey",
  },
  {
    id: 3,
    ingredient_1: "Gesang Gey",
    ingredient_2: "Gesang Gey",
    ingredient_3: "Gesang Gey",
    ingredient_4: "Gesang Gey",
    ingredient_5: "Gesang Gey",
    ingredient_6: "Gesang Gey",
    ingredient_7: "Gesang Gey",
    ingredient_8: "Gesang Gey",
    ingredient_9: "Gesang Gey",
    ingredient_10: "Gesang Gey",
    ingredient_11: "Gesang Gey",
    ingredient_12: "Gesang Gey",
    ingredient_13: "Gesang Gey",
    ingredient_14: "Gesang Gey",
    ingredient_15: "Gesang Gey",
    ingredient_16: "Gesang Gey",
    ingredient_17: "Gesang Gey",
    ingredient_18: "Gesang Gey",
    ingredient_19: "Gesang Gey",
    ingredient_20: "Gesang Gey",
  },
];
