export const ingredients = [
  {
    id: 1,
    ingredient_1: "Water",
    ingredient_2: "Granulated sugar",
    ingredient_3: "Large egg yolk",
    ingredient_4: "Whole large egg",
    ingredient_5: "Can sweetened consensed milk",
    ingredient_6: "Heavy cream",
    ingredient_7: "Vanilla extract",
    ingredient_8: "Kosher salt",
    ingredient_9: null,
    ingredient_10: null,
    ingredient_11: null,
    ingredient_12: null,
    ingredient_13: null,
    ingredient_14: null,
    ingredient_15: null,
    ingredient_16: null,
    ingredient_17: null,
    ingredient_18: null,
    ingredient_19: null,
    ingredient_20: null,
  },
  {
    id: 2,
    ingredient_1: "white bread, crusts removed, cut into cubes",
    ingredient_2: "milk",
    ingredient_3: "butter, divided",
    ingredient_4: "large yellow or white onion, grated using the large holes of a box grater",
    ingredient_5: "large egg",
    ingredient_6: "ground beef",
    ingredient_7: "ground pork",
    ingredient_8: "kosher salt",
    ingredient_9: "black pepper",
    ingredient_10: "freshly grated nutmeg",
    ingredient_11: "ground cardamom",
    ingredient_12: "butter",
    ingredient_13: "flour",
    ingredient_14: "beef stock",
    ingredient_15: "sour cream (use full-fat or the sauce may curdle)",
    ingredient_16: "lingonberry, red currant, raspberry, or cranberry jelly, to taste (optional)",
    ingredient_17: "Salt and pepper, to taste",
    ingredient_18: null,
    ingredient_19: null,
    ingredient_20: null,
  },
  {
    id: 3,
    ingredient_1: "Bacon (reguler or thick-cut)",
    ingredient_2: null,
    ingredient_3: null,
    ingredient_4: null,
    ingredient_5: null,
    ingredient_6: null,
    ingredient_7: null,
    ingredient_8: null,
    ingredient_9: null,
    ingredient_10: null,
    ingredient_11: null,
    ingredient_12: null,
    ingredient_13: null,
    ingredient_14: null,
    ingredient_15: null,
    ingredient_16: null,
    ingredient_17: null,
    ingredient_18: null,
    ingredient_19: null,
    ingredient_20: null,
  },
  {
    id: 4,
    ingredient_1: "loaf Cuban or Italian bread",
    ingredient_2: "unsalted butter, softened",
    ingredient_3: "small clove garlic, crushed",
    ingredient_4: "yellow mustard",
    ingredient_5: "thinly sliced Swiss cheese, about 10 slices",
    ingredient_6: "shredded pork roast, heated until warmed through",
    ingredient_7: "Sliced dill pickles, as needed",
    ingredient_8: "Black Forest or smoked ham",
    ingredient_9: null,
    ingredient_10: null,
    ingredient_11: null,
    ingredient_12: null,
    ingredient_13: null,
    ingredient_14: null,
    ingredient_15: null,
    ingredient_16: null,
    ingredient_17: null,
    ingredient_18: null,
    ingredient_19: null,
    ingredient_20: null,
  },
  {
    id: 5,
    ingredient_1: "raw almonds",
    ingredient_2: "green cardamom pods",
    ingredient_3: "freshly cracked peppercorn",
    ingredient_4: "cinnamon stick",
    ingredient_5: "whole cloves",
    ingredient_6: "leaf",
    ingredient_7: "ground coriander",
    ingredient_8: "salt, or to taste",
    ingredient_9: "plain yogurt",
    ingredient_10: "shredded coconut, optional",
    ingredient_11: "Silvered almonds and chopped cilantro, for garnish",
    ingredient_12: "boneless chicken thighs, cut into 2-inch pieces",
    ingredient_13: "plain yogurt",
    ingredient_14: "ground turmeric",
    ingredient_15: "ginger garlic paste",
    ingredient_16: "salt",
    ingredient_17: "cayenne pepper",
    ingredient_18: "medium onion, thinly sliced, about 1 cup",
    ingredient_19: "vegetable oil",
    ingredient_20: null,
  },
  {
    id: 6,
    ingredient_1: "spinach, rinsed",
    ingredient_2: "scallions, thinly sliced",
    ingredient_3: "garlic, finely chopped",
    ingredient_4: "toasted sesame seeds",
    ingredient_5: "toasted sesame oil",
    ingredient_6: "sugar",
    ingredient_7: "kosher salt",
    ingredient_8: null,
    ingredient_9: null,
    ingredient_10: null,
    ingredient_11: null,
    ingredient_12: null,
    ingredient_13: null,
    ingredient_14: null,
    ingredient_15: null,
    ingredient_16: null,
    ingredient_17: null,
    ingredient_18: null,
    ingredient_19: null,
    ingredient_20: null,
  },
  {
    id: 7,
    ingredient_1: "dried precut wakame seaweed",
    ingredient_2: "piece of dried kelp (kombu)",
    ingredient_3: "water",
    ingredient_4: "large dried bonito flakes (katsuobushi), lightly packed",
    ingredient_5: "white miso paste",
    ingredient_6: "package silken tofu, cut into 1-inch cubes",
    ingredient_7: "sesame oil",
    ingredient_8: "scallion, thinly sliced",
    ingredient_9: "shichimi togarashi (optional)",
    ingredient_10: null,
    ingredient_11: null,
    ingredient_12: null,
    ingredient_13: null,
    ingredient_14: null,
    ingredient_15: null,
    ingredient_16: null,
    ingredient_17: null,
    ingredient_18: null,
    ingredient_19: null,
    ingredient_20: null,
  },
  {
    id: 8,
    ingredient_1: "whole chicken, bone-in, skin-on, cut into 8 pieces",
    ingredient_2: "cup apple cider vinegar",
    ingredient_3: "cup soy sauce",
    ingredient_4: "black peppercorns, crushed",
    ingredient_5: "leaves",
    ingredient_6: "Cloves from 1 whole head of garlic, peeled, halved if large",
    ingredient_7: "chicken broth or water",
    ingredient_8: "Salt to taste",
    ingredient_9: "vegetable oil, for frying",
    ingredient_10: "Steamed rice, for serving",
    ingredient_11: null,
    ingredient_12: null,
    ingredient_13: null,
    ingredient_14: null,
    ingredient_15: null,
    ingredient_16: null,
    ingredient_17: null,
    ingredient_18: null,
    ingredient_19: null,
    ingredient_20: null,
  },
  {
    id: 9,
    ingredient_1: "pizza dough, store-bought or homemade",
    ingredient_2: "pizza sauce",
    ingredient_3: "pepperoni",
    ingredient_4: "mozzarella cheese, grated",
    ingredient_5: "ground black pepper",
    ingredient_6: "fresh oregano, optional",
    ingredient_7: "Flour for rolling and shaping dough",
    ingredient_8: "tomato sauce",
    ingredient_9: "kosher salt",
    ingredient_10: "ground black pepper",
    ingredient_11: "granulated garlic",
    ingredient_12: "granulated onion",
    ingredient_13: "red pepper flakes",
    ingredient_14: "olive oil",
    ingredient_15: "softened butter",
    ingredient_16: "honey",
    ingredient_17: null,
    ingredient_18: null,
    ingredient_19: null,
    ingredient_20: null,
  },
  {
    id: 10,
    ingredient_1: "extra virgin olive oil or unsalted butter",
    ingredient_2: "pancetta or thick cut bacon, diced",
    ingredient_3: "garlic cloves, minced, about 1 teaspoon (optional)",
    ingredient_4: "whole eggs",
    ingredient_5: "grated Parmesan or pecorino cheese",
    ingredient_6: "spaghetti (or bucatini or fettuccine)",
    ingredient_7: "Kosher salt and freshly ground black pepper to taste",
    ingredient_8: null,
    ingredient_9: null,
    ingredient_10: null,
    ingredient_11: null,
    ingredient_12: null,
    ingredient_13: null,
    ingredient_14: null,
    ingredient_15: null,
    ingredient_16: null,
    ingredient_17: null,
    ingredient_18: null,
    ingredient_19: null,
    ingredient_20: null,
  },
  {
    id: 11,
    ingredient_1: "Roma (aka plum) tomatoes",
    ingredient_2: "kosher salt, plus more for salting the pasta water",
    ingredient_3: "extra virgin olive oil",
    ingredient_4: "homemade or store-bought basil pesto, plus more to taste",
    ingredient_5: "dry fusilli pasta",
    ingredient_6: "freshly grated Parmesan cheese, to pass around at the table",
    ingredient_7: null,
    ingredient_8: null,
    ingredient_9: null,
    ingredient_10: null,
    ingredient_11: null,
    ingredient_12: null,
    ingredient_13: null,
    ingredient_14: null,
    ingredient_15: null,
    ingredient_16: null,
    ingredient_17: null,
    ingredient_18: null,
    ingredient_19: null,
    ingredient_20: null,
  },
  {
    id: 12,
    ingredient_1: "unsalted butter",
    ingredient_2: "herbed goat cheese",
    ingredient_3: "thick white bread slices",
    ingredient_4: "sharp white cheddar cheese slices",
    ingredient_5: "provolone cheese slices",
    ingredient_6: "Swiss cheese slices",
    ingredient_7: null,
    ingredient_8: null,
    ingredient_9: null,
    ingredient_10: null,
    ingredient_11: null,
    ingredient_12: null,
    ingredient_13: null,
    ingredient_14: null,
    ingredient_15: null,
    ingredient_16: null,
    ingredient_17: null,
    ingredient_18: null,
    ingredient_19: null,
    ingredient_20: null,
  },
];