export const ingredients = [
  {
    id: 1,
    ingredient_1: "Water",
    ingredient_2: "Granulated sugar",
    ingredient_3: "Large egg yolk",
    ingredient_4: "Whole large egg",
    ingredient_5: "Can sweetened consensed milk",
    ingredient_6: "Heavy cream",
    ingredient_7: "Vanilla extract",
    ingredient_8: "Kosher salt",
    ingredient_9: null,
    ingredient_10: null,
    ingredient_11: null,
    ingredient_12: null,
    ingredient_13: null,
    ingredient_14: null,
    ingredient_15: null,
    ingredient_16: null,
    ingredient_17: null,
    ingredient_18: null,
    ingredient_19: null,
    ingredient_20: null,
  },
  {
    id: 2,
    ingredient_1: "white bread, crusts removed, cut into cubes",
    ingredient_2: "milk",
    ingredient_3: "butter, divided",
    ingredient_4: "large yellow or white onion, grated using the large holes of a box grater",
    ingredient_5: "large egg",
    ingredient_6: "ground beef",
    ingredient_7: "ground pork",
    ingredient_8: "kosher salt",
    ingredient_9: "black pepper",
    ingredient_10: "freshly grated nutmeg",
    ingredient_11: "ground cardamom",
    ingredient_12: "butter",
    ingredient_13: "flour",
    ingredient_14: "beef stock",
    ingredient_15: "sour cream (use full-fat or the sauce may curdle)",
    ingredient_16: "lingonberry, red currant, raspberry, or cranberry jelly, to taste (optional)",
    ingredient_17: "Salt and pepper, to taste",
    ingredient_18: null,
    ingredient_19: null,
    ingredient_20: null,
  },
  {
    id: 3,
    ingredient_1: "Bacon (reguler or thick-cut)",
    ingredient_2: null,
    ingredient_3: null,
    ingredient_4: null,
    ingredient_5: null,
    ingredient_6: null,
    ingredient_7: null,
    ingredient_8: null,
    ingredient_9: null,
    ingredient_10: null,
    ingredient_11: null,
    ingredient_12: null,
    ingredient_13: null,
    ingredient_14: null,
    ingredient_15: null,
    ingredient_16: null,
    ingredient_17: null,
    ingredient_18: null,
    ingredient_19: null,
    ingredient_20: null,
  },
];