export const measures = [
  {
    id: 1,
    measure_1: "Gesang Gey",
    measure_2: "Gesang Gey",
    measure_3: "Gesang Gey",
    measure_4: "Gesang Gey",
    measure_5: "Gesang Gey",
    measure_6: "Gesang Gey",
    measure_7: "Gesang Gey",
    measure_8: "Gesang Gey",
    measure_9: "Gesang Gey",
    measure_10: "Gesang Gey",
    measure_11: "Gesang Gey",
    measure_12: "Gesang Gey",
    measure_13: "Gesang Gey",
    measure_14: "Gesang Gey",
    measure_15: "Gesang Gey",
    measure_16: "Gesang Gey",
    measure_17: "Gesang Gey",
    measure_18: "Gesang Gey",
    measure_19: "Gesang Gey",
    measure_20: "Gesang Gey",
  },
  {
    id: 2,
    measure_1: "Gesang Gey",
    measure_2: "Gesang Gey",
    measure_3: "Gesang Gey",
    measure_4: "Gesang Gey",
    measure_5: "Gesang Gey",
    measure_6: "Gesang Gey",
    measure_7: "Gesang Gey",
    measure_8: "Gesang Gey",
    measure_9: "Gesang Gey",
    measure_10: "Gesang Gey",
    measure_11: "Gesang Gey",
    measure_12: "Gesang Gey",
    measure_13: "Gesang Gey",
    measure_14: "Gesang Gey",
    measure_15: "Gesang Gey",
    measure_16: "Gesang Gey",
    measure_17: "Gesang Gey",
    measure_18: "Gesang Gey",
    measure_19: "Gesang Gey",
    measure_20: "Gesang Gey",
  },
  {
    id: 3,
    measure_1: "Gesang Gey",
    measure_2: "Gesang Gey",
    measure_3: "Gesang Gey",
    measure_4: "Gesang Gey",
    measure_5: "Gesang Gey",
    measure_6: "Gesang Gey",
    measure_7: "Gesang Gey",
    measure_8: "Gesang Gey",
    measure_9: "Gesang Gey",
    measure_10: "Gesang Gey",
    measure_11: "Gesang Gey",
    measure_12: "Gesang Gey",
    measure_13: "Gesang Gey",
    measure_14: "Gesang Gey",
    measure_15: "Gesang Gey",
    measure_16: "Gesang Gey",
    measure_17: "Gesang Gey",
    measure_18: "Gesang Gey",
    measure_19: "Gesang Gey",
    measure_20: "Gesang Gey",
  },
];
