export const measures = [
  {
    id: 1,
    measure_1: "2 tablespoons",
    measure_2: "1/2 cup granulated sugar",
    measure_3: "4",
    measure_4: "1",
    measure_5: "1 can",
    measure_6: "2 cups",
    measure_7: "1 tablespoon",
    measure_8: "1/4 teaspoon",
    measure_9: null,
    measure_10: null,
    measure_11: null,
    measure_12: null,
    measure_13: null,
    measure_14: null,
    measure_15: null,
    measure_16: null,
    measure_17: null,
    measure_18: null,
    measure_19: null,
    measure_20: null,
  },
  {
    id: 2,
    measure_1: "3 slices",
    measure_2: "1/4 cup",
    measure_3: "4 tablespoons",
    measure_4: "1/2 large",
    measure_5: "1 large",
    measure_6: "3/4 pound",
    measure_7: "1/2 pound",
    measure_8: "1 teaspoon",
    measure_9: "1 teaspoon",
    measure_10: "1/2 teaspoon",
    measure_11: "1/2 teaspoon",
    measure_12: "3 tablespoons",
    measure_13: "3 tablespoons",
    measure_14: "2 cups",
    measure_15: "1/4 cup",
    measure_16: "2 tablespoons",
    measure_17: null,
    measure_18: null,
    measure_19: null,
    measure_20: null,
  },
  {
    id: 3,
    measure_1: "4 slices",
    measure_2: null,
    measure_3: null,
    measure_4: null,
    measure_5: null,
    measure_6: null,
    measure_7: null,
    measure_8: null,
    measure_9: null,
    measure_10: null,
    measure_11: null,
    measure_12: null,
    measure_13: null,
    measure_14: null,
    measure_15: null,
    measure_16: null,
    measure_17: null,
    measure_18: null,
    measure_19: null,
    measure_20: null,
  },
  {
    id: 4,
    measure_1: "1 pound",
    measure_2: "2 tablespoons",
    measure_3: "1",
    measure_4: "2 tablespoons",
    measure_5: "8 ounces",
    measure_6: "1 pound",
    measure_7: null,
    measure_8: "10 slices",
    measure_9: null,
    measure_10: null,
    measure_11: null,
    measure_12: null,
    measure_13: null,
    measure_14: null,
    measure_15: null,
    measure_16: null,
    measure_17: null,
    measure_18: null,
    measure_19: null,
    measure_20: null,
  },
  {
    id: 5,
    measure_1: "1 1/4 pounds",
    measure_2: "6 tablespoons",
    measure_3: "1/2 tablespoon",
    measure_4: "3 cloves",
    measure_5: "1 teaspoon",
    measure_6: "1 teaspoon",
    measure_7: "1 1/4 teaspoons",
    measure_8: null,
    measure_9: null,
    measure_10: null,
    measure_11: null,
    measure_12: null,
    measure_13: null,
    measure_14: null,
    measure_15: null,
    measure_16: null,
    measure_17: null,
    measure_18: null,
    measure_19: null,
    measure_20: null,
  },
  {
    id: 5,
    measure_1: "12 to 15",
    measure_2: "2 to 3",
    measure_3: "1/2 teaspoon",
    measure_4: "1-inch",
    measure_5: "2 to 3",
    measure_6: "1 bay",
    measure_7: "1 tablespoon",
    measure_8: "1/2 teaspoon",
    measure_9: "1/4 cup",
    measure_10: "1 1/2 teaspoon",
    measure_11: null,
    measure_12: "1 1/2 pounds",
    measure_13: "2 tablespoons",
    measure_14: "1/2 teaspoon",
    measure_15: "1 1/2 tablespoons",
    measure_16: "1/2 teaspoon",
    measure_17: "1 teaspoon",
    measure_18: "1",
    measure_19: "1/2 cup",
    measure_20: null,
  },
  {
    id: 6,
    measure_1: "2 large bunches (14 ounces)",
    measure_2: "3",
    measure_3: "3 cloves",
    measure_4: "1 tablespoon",
    measure_5: "2 tablespoons",
    measure_6: "2 teaspoons",
    measure_7: "1/2 teaspoon",
    measure_8: null,
    measure_9: null,
    measure_10: null,
    measure_11: null,
    measure_12: null,
    measure_13: null,
    measure_14: null,
    measure_15: null,
    measure_16: null,
    measure_17: null,
    measure_18: null,
    measure_19: null,
    measure_20: null,
  },
  {
    id: 7,
    measure_1: "2 tablespoon",
    measure_2: "1 (14x2 1/2-inch)",
    measure_3: "8 cups",
    measure_4: "2 cups (20g)",
    measure_5: "1/3 cup",
    measure_6: "1 (16 ounce)",
    measure_7: "2 teaspoons",
    measure_8: "1",
    measure_9: "1/8 teaspoon",
    measure_10: null,
    measure_11: null,
    measure_12: null,
    measure_13: null,
    measure_14: null,
    measure_15: null,
    measure_16: null,
    measure_17: null,
    measure_18: null,
    measure_19: null,
    measure_20: null,
  },
  {
    id: 8,
    measure_1: "1 (3 to 4 pound)",
    measure_2: "1 cup",
    measure_3: "1/4 cup",
    measure_4: "1 teaspoon",
    measure_5: "2 bay",
    measure_6: "10 to 12",
    measure_7: "2 cups",
    measure_8: null,
    measure_9: "1/4 cup",
    measure_10: null,
    measure_11: null,
    measure_12: null,
    measure_13: null,
    measure_14: null,
    measure_15: null,
    measure_16: null,
    measure_17: null,
    measure_18: null,
    measure_19: null,
    measure_20: null,
  },
  {
    id: 9,
    measure_1: "16 ounces",
    measure_2: "1/2 cup",
    measure_3: "18 to 20 slices",
    measure_4: "12 ounces",
    measure_5: "1/2 teaspoon",
    measure_6: "1 teaspoon",
    measure_7: null,
    measure_8: "1/2 cup",
    measure_9: "1/2 teaspoon",
    measure_10: "1/2 teaspoon",
    measure_11: "1/2 teaspoon",
    measure_12: "1/2 teaspoon",
    measure_13: "1/4 teaspoon",
    measure_14: "1 teaspoon",
    measure_15: "1/4 cup",
    measure_16: "2 tablespoons",
    measure_17: null,
    measure_18: null,
    measure_19: null,
    measure_20: null,
  },
  {
    id: 10,
    measure_1: "1 tablespoon",
    measure_2: "1/2 pound",
    measure_3: "1 teaspoon",
    measure_4: "3 to 4",
    measure_5: "1 cup",
    measure_6: "1 pound",
    measure_7: "To taste",
    measure_8: null,
    measure_9: null,
    measure_10: null,
    measure_11: null,
    measure_12: null,
    measure_13: null,
    measure_14: null,
    measure_15: null,
    measure_16: null,
    measure_17: null,
    measure_18: null,
    measure_19: null,
    measure_20: null,
  },
  {
    id: 11,
    measure_1: "2 1/4 pounds",
    measure_2: "1 1/2 teaspoons",
    measure_3: "1/4 cup",
    measure_4: "1/4 cup",
    measure_5: "1 pound",
    measure_6: "1/3 cup",
    measure_7: null,
    measure_8: null,
    measure_9: null,
    measure_10: null,
    measure_11: null,
    measure_12: null,
    measure_13: null,
    measure_14: null,
    measure_15: null,
    measure_16: null,
    measure_17: null,
    measure_18: null,
    measure_19: null,
    measure_20: null,
  },
  {
    id: 12,
    measure_1: "6 tablespoons (3 ounces)",
    measure_2: "2 tablespoons",
    measure_3: "10 slices",
    measure_4: "5 slices",
    measure_5: "5 slices",
    measure_6: "5 slices",
    measure_7: null,
    measure_8: null,
    measure_9: null,
    measure_10: null,
    measure_11: null,
    measure_12: null,
    measure_13: null,
    measure_14: null,
    measure_15: null,
    measure_16: null,
    measure_17: null,
    measure_18: null,
    measure_19: null,
    measure_20: null,
  },
];