export const measures = [
  {
    id: 1,
    measure_1: "2 tablespoons",
    measure_2: "1/2 cup granulated sugar",
    measure_3: "4",
    measure_4: "1",
    measure_5: "1 can",
    measure_6: "2 cups",
    measure_7: "1 tablespoon",
    measure_8: "1/4 teaspoon",
    measure_9: null,
    measure_10: null,
    measure_11: null,
    measure_12: null,
    measure_13: null,
    measure_14: null,
    measure_15: null,
    measure_16: null,
    measure_17: null,
    measure_18: null,
    measure_19: null,
    measure_20: null,
  },
  {
    id: 2,
    measure_1: "3 slices",
    measure_2: "1/4 cup",
    measure_3: "4 tablespoons",
    measure_4: "1/2 large",
    measure_5: "1 large",
    measure_6: "3/4 pound",
    measure_7: "1/2 pound",
    measure_8: "1 teaspoon",
    measure_9: "1 teaspoon",
    measure_10: "1/2 teaspoon",
    measure_11: "1/2 teaspoon",
    measure_12: "3 tablespoons",
    measure_13: "3 tablespoons",
    measure_14: "2 cups",
    measure_15: "1/4 cup",
    measure_16: "2 tablespoons",
    measure_17: null,
    measure_18: null,
    measure_19: null,
    measure_20: null,
  },
  {
    id: 3,
    measure_1: "4 slices",
    measure_2: null,
    measure_3: null,
    measure_4: null,
    measure_5: null,
    measure_6: null,
    measure_7: null,
    measure_8: null,
    measure_9: null,
    measure_10: null,
    measure_11: null,
    measure_12: null,
    measure_13: null,
    measure_14: null,
    measure_15: null,
    measure_16: null,
    measure_17: null,
    measure_18: null,
    measure_19: null,
    measure_20: null,
  },
];