export const steps = [
  {
    id: 1,
    step_1: "Gesang Gey",
    step_2: "Gesang Gey",
    step_3: "Gesang Gey",
    step_4: "Gesang Gey",
    step_5: "Gesang Gey",
    step_6: "Gesang Gey",
    step_7: "Gesang Gey",
    step_8: "Gesang Gey",
    step_9: "Gesang Gey",
    step_10: "Gesang Gey",
    step_11: "Gesang Gey",
    step_12: "Gesang Gey",
    step_13: "Gesang Gey",
    step_14: "Gesang Gey",
    step_15: "Gesang Gey",
    step_16: "Gesang Gey",
    step_17: "Gesang Gey",
    step_18: "Gesang Gey",
    step_19: "Gesang Gey",
    step_20: "Gesang Gey",
  },
  {
    id: 2,
    step_1: "Gesang Gey",
    step_2: "Gesang Gey",
    step_3: "Gesang Gey",
    step_4: "Gesang Gey",
    step_5: "Gesang Gey",
    step_6: "Gesang Gey",
    step_7: "Gesang Gey",
    step_8: "Gesang Gey",
    step_9: "Gesang Gey",
    step_10: "Gesang Gey",
    step_11: "Gesang Gey",
    step_12: "Gesang Gey",
    step_13: "Gesang Gey",
    step_14: "Gesang Gey",
    step_15: "Gesang Gey",
    step_16: "Gesang Gey",
    step_17: "Gesang Gey",
    step_18: "Gesang Gey",
    step_19: "Gesang Gey",
    step_20: "Gesang Gey",
  },
  {
    id: 3,
    step_1: "Gesang Gey",
    step_2: "Gesang Gey",
    step_3: "Gesang Gey",
    step_4: "Gesang Gey",
    step_5: "Gesang Gey",
    step_6: "Gesang Gey",
    step_7: "Gesang Gey",
    step_8: "Gesang Gey",
    step_9: "Gesang Gey",
    step_10: "Gesang Gey",
    step_11: "Gesang Gey",
    step_12: "Gesang Gey",
    step_13: "Gesang Gey",
    step_14: "Gesang Gey",
    step_15: "Gesang Gey",
    step_16: "Gesang Gey",
    step_17: "Gesang Gey",
    step_18: "Gesang Gey",
    step_19: "Gesang Gey",
    step_20: "Gesang Gey",
  },
];
