export const steps = [
  {
    id: 1,
    step_1: "Preheat the oven to 300 Fahrenheit. Set the rack in the center of the oven. Bring about 40 ounces (5 cups) of water to a boil for the water bath that you’ll use to bake the flan.",
    step_2: "Make the caramel sauce. Add 2 tablespoons water and the sugar in a small saucepan. Swirl it just a bit until all the sugar looks wet. Set it over medium heat, and cook without stirring until the mixture bubbles vigorously and turns from pale to light brown, then amber to dark amber. It should look glossy and smooth, not grainy. This takes 4 to 6 minutes, depending on the strength of your stove. If crystals start to form in the caramel, it's best to start over. There's no way to fix this. In the meantime, have an 8x2-inch round cake pan and a kitchen towel ready. Carefully pour the caramel into the cake pan and working quickly tilt the pan to swirl and coat the bottom and sides. Hold on to the sides with a kitchen towel—there is nothing more painful than molten sugar. Set the pan aside.",
    step_3: "Make the custard. In a 4-cup measuring cup or medium bowl, whisk the egg yolks, whole egg, and sweetened condensed milk until fully combined. Whisk in the heavy cream, vanilla, and salt. The custard should be smooth and thoroughly combined, but try not to whisk it vigorously, creating too many bubbles.",
    step_4: "Prepare the water bath. Pour the custard through a  fine mesh strainer over the caramel in the pan. Place the pan into an oven-safe vessel large enough to hold it—a roasting pan, baking dish, or shallow braiser with straight sides, and place it in the oven. Pour the boiling water into the roasting dish until it comes about halfway up the sides of the cake pan.",
    step_5: "Bake the flan. Bake the flan until the top is set and no longer wet, but a little jiggly when you gently nudge the cake pan, about 1 hour 20 minutes.",
    step_6: "Chill the flan. Carefully remove the cake pan from the water bath (use a kitchen towel) and let it cool for about 1 hour on the kitchen counter. Tightly cover the pan with plastic wrap, making sure it doesn’t touch the top of the flan. Chill in the fridge for at least 6 hours or overnight.",
    step_7: "Serve the flan. When ready to serve (flan should be served cold), run a small knife around the edges to loosen the flan. Flip a large, deep plate upside down on top of the cake pan. In one swift movement, invert the cake pan and plate. Give the bottom of the cake pan a couple of firm taps to help release the flan onto the plate. Gently lift the cake pan and marvel at your work of art. It’s okay if some caramel is still stuck to the cake pan. Soak it in water for a few minutes, and it’ll melt off. Keep leftovers refrigerated for up to 4 days, tightly covered.",
    step_8: null,
    step_9: null,
    step_10: null,
    step_11: null,
    step_12: null,
    step_13: null,
    step_14: null,
    step_15: null,
    step_16: null,
    step_17: null,
    step_18: null,
    step_19: null,
    step_20: null,
  },
  {
    id: 2,
    step_1: "Soak the bread in milk, then shred: Place the cubed bread in a large bowl and mix with the milk. Let sit for 5 to 10 minutes. Once the bread has soaked up all the milk, shred with the tines of a fork or by hand.",
    step_2: "Sauté the grated onion: Melt 1 tablespoon of butter in a sauté pan on medium-high heat. Stir in the grated onion and cook until translucent and softened, 3 to 4 minutes. Remove from the heat and let cool for a minute.",
    step_3: "Make the meatball mixture. Stir the cooled onions into the milk bread mixture. Add the egg, ground beef and pork, salt, pepper, nutmeg, and cardamom. Use your (clean) hands to mix everything together until well combined. (If you have extra time, chilling the mixture for 20 or so minutes will make it easier to roll out the meatballs.)",
    step_4: "Form the meatballs: Use your hands to form the mixture into meatballs about 1 1/4-inch to 1 1/2-inch wide and place them on a plate or sheet pan. This recipe should make about 40 meatballs. Note that the meatballs will be a bit on the wet side.",
    step_5: "Brown the meatballs on all sides: Heat 3 tablespoons of butter in a large sauté pan on medium heat. When the butter is melted and foamy, start adding some meatballs to the pan. Working in batches as to not crowd the pan, slowly brown the meatballs on all sides. Use a wooden spoon or tongs to turn them. Handle the meatballs gently so they do not break apart as you turn them. Once the meatballs have browned on all sides and are just cooked through, remove them from the pan to a bowl. You'll warm the meatballs in the sauce later. Once you have removed the meatballs from the pan, wipe out the butter and blackened bits with a paper towel. We'll want to start with fresh butter so we don't pick up any burnt bits from the pan. This way, we will be able to more accurately gauge the amount of fat in the pan for making the meatball sauce in the next step.",
    step_6: "Make a roux: Add 3 tablespoons of fresh butter to the pan. Heat the butter in the pan on medium heat until it melts and starts to bubble. Slowly whisk in 3 tablespoons of flour. Stir until smooth. Continue to stir, allowing the flour mixture to cook, several minutes, until the roux is the color of coffee with cream.",
    step_7: "Add stock to make the sauce: When the roux has cooked to a lovely shade of light brown, slowly add the stock, stirring as you do. The stock will sputter at first and the roux may seize up, but keep adding the stock slowly and keep stirring. Eventually the sauce will loosen and become silky.",
    step_8: "Stir in the sour cream and optional jelly: Remove the pan from heat and stir in the sour cream. If you are including jelly, either stir it in now or serve it on the side. Taste for seasonings and add more salt and pepper to taste. (I use about 1/2 teaspoon of kosher salt, and 1/4 teaspoon of pepper.)",
    step_9: "Heat the meatballs in the sauce: Return the meatballs to the pan with the sauce and cook on low heat to warm them through for a few minutes.",
    step_10: "Serve fresh from the pan: Serve over mashed potatoes or egg noodles. Or serve individual Swedish meatballs dipped in gravy as an appetizer.",
    step_11: null,
    step_12: null,
    step_13: null,
    step_14: null,
    step_15: null,
    step_16: null,
    step_17: null,
    step_18: null,
    step_19: null,
    step_20: null,
  },
  {
    id: 3,
    step_1: "Put the bacon on a paper towel-lined plate: Line a microwave-safe plate with 2 layers of paper towels. Place the bacon on top, without overlapping. Cover with another 2 layers of paper towels.",
    step_2: "Microwave the bacon: Microwave on HIGH for 2 minutes for regular bacon or 2 minutes 30 seconds for thick-cut bacon.",
    step_3: "Flip the bacon: Peel back the top layer of paper towels and use tongs to flip the bacon strips. Microwave another 2 minutes for regular and 2 minutes 30 seconds for thick-cut, until the bacon is deep golden-brown and crispy.",
    step_4: "Serve: Remove the bacon from the paper towels, being mindful of hot grease, and place on a clean plate. Serve.",
    step_5: null,
    step_6: null,
    step_7: null,
    step_8: null,
    step_9: null,
    step_10: null,
    step_11: null,
    step_12: null,
    step_13: null,
    step_14: null,
    step_15: null,
    step_16: null,
    step_17: null,
    step_18: null,
    step_19: null,
    step_20: null,
  },
];