import Joi from "joi"

export const loginSchema = Joi.object({
    email: Joi.string().email().required(),
    password: Joi.string().required()
})

export const userSchema = Joi.object({
    username: Joi.string().required(),
    email: Joi.string().email().required(),
    password: Joi.string().required(),
})

export const recipeSchema = Joi.object({
    name: Joi.string().required(),
    description: Joi.string().required(),
    category: Joi.string().required().valid('Beef', 'Chicken', 'Seafood', 'Vegetarian', 'Pork', 'Lamb', 'Turkey', 'Pasta', 'Rice', 'Soup', 'Sandwiches', 'Salads', 'Pizza', 'Desserts'),
    vegan: Joi.boolean().required(),
    cookTime: Joi.number().integer().required(),
    thumbnail: Joi.string().required(),
    origin: Joi.string().required().valid('Asian', 'MiddleEastern', 'Indian', 'African', 'LatinAmerican', 'Mediterranean', 'Western', 'SoutheastAsian', 'EasternEuropean', 'Scandinavian'),
    ingredient1: Joi.string().required(),
    ingredient2: Joi.string().allow(null),
    ingredient3: Joi.string().allow(null),
    ingredient4: Joi.string().allow(null),
    ingredient5: Joi.string().allow(null),
    ingredient6: Joi.string().allow(null),
    ingredient7: Joi.string().allow(null),
    ingredient8: Joi.string().allow(null),
    ingredient9: Joi.string().allow(null),
    ingredient10: Joi.string().allow(null),
    ingredient11: Joi.string().allow(null),
    ingredient12: Joi.string().allow(null),
    ingredient13: Joi.string().allow(null),
    ingredient14: Joi.string().allow(null),
    ingredient15: Joi.string().allow(null),
    ingredient16: Joi.string().allow(null),
    ingredient17: Joi.string().allow(null),
    ingredient18: Joi.string().allow(null),
    ingredient19: Joi.string().allow(null),
    ingredient20: Joi.string().allow(null),
    measure1: Joi.string().required(),
    measure2: Joi.string().allow(null),
    measure3: Joi.string().allow(null),
    measure4: Joi.string().allow(null),
    measure5: Joi.string().allow(null),
    measure6: Joi.string().allow(null),
    measure7: Joi.string().allow(null),
    measure8: Joi.string().allow(null),
    measure9: Joi.string().allow(null),
    measure10: Joi.string().allow(null),
    measure11: Joi.string().allow(null),
    measure12: Joi.string().allow(null),
    measure13: Joi.string().allow(null),
    measure14: Joi.string().allow(null),
    measure15: Joi.string().allow(null),
    measure16: Joi.string().allow(null),
    measure17: Joi.string().allow(null),
    measure18: Joi.string().allow(null),
    measure19: Joi.string().allow(null),
    measure20: Joi.string().allow(null),
    step1: Joi.string().required(),
    step2: Joi.string().allow(null),
    step3: Joi.string().allow(null),
    step4: Joi.string().allow(null),
    step5: Joi.string().allow(null),
    step6: Joi.string().allow(null),
    step7: Joi.string().allow(null),
    step8: Joi.string().allow(null),
    step9: Joi.string().allow(null),
    step10: Joi.string().allow(null),
    step11: Joi.string().allow(null),
    step12: Joi.string().allow(null),
    step13: Joi.string().allow(null),
    step14: Joi.string().allow(null),
    step15: Joi.string().allow(null),
    step16: Joi.string().allow(null),
    step17: Joi.string().allow(null),
    step18: Joi.string().allow(null),
    step19: Joi.string().allow(null),
    step20: Joi.string().allow(null),
    userId: Joi.number().integer().required(),
})
